site:
  assetPath: /assets
  atomPath: /atom
  rssPath: /rss
  sourcePath: /Users/bpillow/Git/WebSites/CruZionsville
  destinationPath: /Users/bpillow/Git/WebSitesDeploy/CruZionsville
  brand : CruZionsville
  navBarInverse : true
  navBarBrandImage: /content/banner/BrandLogo.jpg

  author:
    name: Stephen Tarr
    company: CruZionsville
    email: suport@cruzionsville.com

  previewPort: 8080

  appearance:
    emphasizeHomePageTitle: true

  time: 2014-05-07